name: PR-CI

# Controls when the workflow will run
on:
  push
  pull_request

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install with pnpm
        run: curl -f https://get.pnpm.io/v6.7.js | node - add --global pnpm && pnpm install

      - name: Prettier, jest, lint, static type check
        run: pnpm check
        
